/**
 * Builds src/embeds_data.h — a header file containing gzip-compressed byte
 * arrays for the web assets embedded in src/SPIFFSEditor.cpp (edit.htm + the
 * Ace editor + its HTML/JSON modes and workers).
 *
 * How to use it?
 *
 * 1) Install Node 11+
 * 2) npm install   (no third-party packages required — uses Node's built-in zlib)
 * 3) npm run build
 *
 * The script writes src/embeds_data.h. SPIFFSEditor.cpp #includes it directly:
 *   #include "embeds_data.h"
 * so no manual copy/paste step is needed.
 */

const fs = require("fs");
const path = require("path");
const zlib = require("zlib");

/**
 * Specs for each embedded asset. `src` is relative to the project root.
 *
 * The `name` is the C identifier — paired with `_len` it produces both:
 *   const uint8_t  <name>[]    PROGMEM = { ... };
 *   const uint32_t <name>_len            = N;
 *
 * Keep these names in sync with the symbols referenced in src/SPIFFSEditor.cpp.
 */
const specs = [
  { src: "embeds/edit.htm",       name: "edit_htm_gz",       mime: "text/html" },
  { src: "embeds/ace.js",         name: "ace_js_gz",         mime: "application/javascript" },
  { src: "embeds/mode-html.js",   name: "mode_html_js_gz",   mime: "application/javascript" },
  { src: "embeds/mode-json.js",   name: "mode_json_js_gz",   mime: "application/javascript" },
  { src: "embeds/worker-html.js", name: "worker_html_js_gz", mime: "application/javascript" },
  { src: "embeds/worker-json.js", name: "worker_json_js_gz", mime: "application/javascript" },
];

const HEADER_GUARD = "EMBEDS_DATA_H";
const OUTPUT_PATH = path.resolve(__dirname, "src/embeds_data.h");

/**
 * Format a Buffer as a C byte-array literal, 16 bytes per line.
 */
function hexdump(buffer) {
  const lines = [];
  for (let i = 0; i < buffer.length; i += 16) {
    const block = buffer.slice(i, i + 16);
    const hex = [];
    for (const v of block) {
      hex.push("0x" + v.toString(16).padStart(2, "0"));
    }
    lines.push("  " + hex.join(", "));
  }
  return lines.join(",\n");
}

/**
 * Gzip-compress a file at level 9 (Z_BEST_COMPRESSION) and emit a C byte-array
 * block matching the style previously used inline in SPIFFSEditor.cpp.
 */
function emitGzippedArray(srcPath, name) {
  const buf = fs.readFileSync(srcPath);
  const gz = zlib.gzipSync(buf, { level: zlib.constants.Z_BEST_COMPRESSION });
  return [
    "// array size is " + gz.length,
    "#define " + name + "_len " + gz.length,
    "static const byte " + name + "[] PROGMEM = {",
    hexdump(gz),
    "};",
  ].join("\n");
}

const out = [];
out.push("// Auto-generated by cdata.js — do not edit by hand.");
out.push("// Run `npm run build` to regenerate.");
out.push("");
out.push("#ifndef " + HEADER_GUARD);
out.push("#define " + HEADER_GUARD);
out.push("");
out.push("#include <Arduino.h>");
out.push("");

let totalIn = 0;
let totalOut = 0;
for (const spec of specs) {
  const srcPath = path.resolve(__dirname, spec.src);
  if (!fs.existsSync(srcPath)) {
    console.error("Missing source file: " + spec.src);
    process.exit(1);
  }
  const inSize = fs.statSync(srcPath).size;
  totalIn += inSize;
  const block = emitGzippedArray(srcPath, spec.name);
  out.push("// Source: " + spec.src + " (" + inSize + " bytes, " + spec.mime + ")");
  out.push(block);
  out.push("");
  const m = block.match(/^#define \S+_len (\d+)$/m);
  const gzSize = m ? parseInt(m[1], 10) : 0;
  totalOut += gzSize;
  console.error(
    spec.src.padEnd(24) +
      " " +
      String(inSize).padStart(7) +
      " bytes -> " +
      String(gzSize).padStart(7) +
      " bytes (gzip, " +
      spec.name +
      ")"
  );
}

out.push("#endif // " + HEADER_GUARD);
out.push("");

fs.writeFileSync(OUTPUT_PATH, out.join("\n"));
console.error("");
console.error("Wrote " + OUTPUT_PATH);
console.error(
  "Total: " + totalIn + " bytes -> " + totalOut + " bytes (gzip)"
);
